version: "3"
services:
  web:
    build: .
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - type: bind
        source: ./pathRoleSettings.json
        target: /usr/src/app/pathRoleSettings.json
      # or
      # - .:/usr/src/app
      # - /usr/src/app/node_modules