version: "3"
services:
  web:
    build: .
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # - type: bind
      #   source: ./.env
      #   target: /usr/src/app/.env
      # - type: bind
      #   source: ./pathRoleSettings.json
      #   target: /usr/src/app/pathRoleSettings.json