version: "3"
services:
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
      # - type: bind
      #   source: ./.env
      #   target: /usr/src/app/.env
      # - type: bind
      #   source: ./pathRoleSettings.js
      #   target: /usr/src/app/pathRoleSettings.js